# Compiler
CXX = g++
CXXFLAGS = -std=c++17 -Wall

# List of programs (each program is linked from main.o + <prog>.o)
PROGRAMS = count_bits parity swap_bits

all: $(PROGRAMS)

# Link rule: build an executable by linking main.o and <prog>.o
%: main.o %.o
    $(CXX) $(CXXFLAGS) $^ -o $@

# Compile .cpp -> .o
%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c $< -o $@

clean:
    rm -f $(PROGRAMS) *.o

.PHONY: all clean $(PROGRAMS)